# On every push this script is executed
on:
  push:
    branches:
      - code
name: Build and deploy GH Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - name: checkout
      uses: actions/checkout@v3.0.0
    # Build & deploy
    - name: build_and_deploy
      uses: shalzz/zola-deploy-action@master
      env:
        # Target branch
        PAGES_BRANCH: main
        # Provide personal access token
        GITHUB_TOKEN: ${{ secrets.TOKEN }}